from dominio.objetos_de_valor.email import Email
from dominio.objetos_de_valor.nome_de_docente import NomeDeDocente
from dominio.objetos_de_valor.id import Id
from dominio.objetos_de_valor.nome_tipo_de_contratacao import NomeTipoDeContratacao
from dominio.objetos_de_valor.nome_unidade_senai import NomeUnidadeSenai
from dominio.objetos_de_valor.telefone import Telefone
from dominio.objetos_de_valor.tipo_de_contratacao import TipoDeContratacao
