from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_email import FabricaTesteEmail
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_id import FabricaTesteId
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_nome_de_docente import FabricaTesteNomeDeDocente
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_nome_generico import FabricaTesteNomeGenerico
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_telefone import FabricaTesteTelefone
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_tipo_de_contratacao import FabricaTesteTipoDeContratacao
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_nome_unidade_senai import FabricaTesteNomeUnidadeSenai
from testes.fabricas.dominio.objetos_de_valor.fabrica_teste_unidade_senai import FabricaTesteUnidadeSenai
