# Generated by Django 4.1 on 2022-12-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloUnidadeSenai',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDocente',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefones', models.CharField(max_length=200)),
                ('tipo_de_contratacao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField()),
                ('unidade_senai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.modelounidadesenai')),
            ],
        ),
    ]
